### ISSUE TITLE
[SEO] tasks for getting seo all ready

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#705]
- [x] analytics (vercel analytics)
- [x] icon favicon sizes for all devices (#728)
- [x] page titles are consistent / validate all static og images (#730)
- [x] dynamic og images for challenge (#671)
- [x] create a site map (#706)
- [x] validate the robots files
- [x] enable IndexNow / crawler hints
- [x] indexed on all the search engines
  - [x] google
  - [x] bing
  - [x] duck duck go
  - [x] yahoo

**Comment by Hacksore** [comment]
![image](https://github.com/typehero/typehero/assets/996134/a27894ac-65ee-4d12-9c1d-e793551ef81f)
